baseURL: https://lxierita.github.io/
languageCode: en-uk
defaultContentLanguage: en
title: Teresa Clarke Accountancy Tutoring
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags
  series: series

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  navTitleText: Teresa Clarke Accountancy Tutoring
  customCss:
    - css/main.css

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Books
      url: /books/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Series
      url: /series/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2